name: Default
main: net.brord.plugins.defaultplugin.Default
version: 0.1
description: description
authors: [kwek20]
depend: []
commands:
  epay:
    description: Pays a player money
    usage: Type /epay [name] [amount]
    aliases: [ep]
permissions:
  name.*:
    description: Gives access to all plugin commands
    children:
     name.reload: true
  name.reload: 
    description: Allows you to reload the plugin